'use client';

import type { IconProps, IconWeight } from '@phosphor-icons/react';

export type { IconProps, IconWeight };

export { House, House as HouseIcon } from '@phosphor-icons/react/dist/ssr/House';
export { CalendarCheck, CalendarCheck as CalendarCheckIcon } from '@phosphor-icons/react/dist/ssr/CalendarCheck';
export { Calendar } from '@phosphor-icons/react/dist/ssr/Calendar';
export { ListChecks, ListChecks as ListChecksIcon } from '@phosphor-icons/react/dist/ssr/ListChecks';
export { ListBullets, ListBullets as ListBulletsIcon } from '@phosphor-icons/react/dist/ssr/ListBullets';
export { UsersThree, UsersThree as UsersThreeIcon } from '@phosphor-icons/react/dist/ssr/UsersThree';
export { UserCheck, UserCheck as UserCheckIcon } from '@phosphor-icons/react/dist/ssr/UserCheck';
export { SquaresFour, SquaresFour as SquaresFourIcon } from '@phosphor-icons/react/dist/ssr/SquaresFour';
export { Gear, Gear as GearIcon } from '@phosphor-icons/react/dist/ssr/Gear';
export { ClipboardText, ClipboardText as ClipboardTextIcon } from '@phosphor-icons/react/dist/ssr/ClipboardText';
export { UserCircle, UserCircle as UserCircleIcon } from '@phosphor-icons/react/dist/ssr/UserCircle';
export { SignOut, SignOut as SignOutIcon } from '@phosphor-icons/react/dist/ssr/SignOut';
export { DotsThree, DotsThree as DotsThreeIcon } from '@phosphor-icons/react/dist/ssr/DotsThree';
export { CheckCircle } from '@phosphor-icons/react/dist/ssr/CheckCircle';
export { Clock } from '@phosphor-icons/react/dist/ssr/Clock';
export { Warning } from '@phosphor-icons/react/dist/ssr/Warning';
export { XCircle } from '@phosphor-icons/react/dist/ssr/XCircle';
export { ArrowsLeftRight } from '@phosphor-icons/react/dist/ssr/ArrowsLeftRight';
export { Bell } from '@phosphor-icons/react/dist/ssr/Bell';
export { WhatsappLogo } from '@phosphor-icons/react/dist/ssr/WhatsappLogo';
export { EnvelopeSimple } from '@phosphor-icons/react/dist/ssr/EnvelopeSimple';
export { Church } from '@phosphor-icons/react/dist/ssr/Church';
export { Cross } from '@phosphor-icons/react/dist/ssr/Cross';
export { HandsPraying } from '@phosphor-icons/react/dist/ssr/HandsPraying';
export { PaperPlaneTilt } from '@phosphor-icons/react/dist/ssr/PaperPlaneTilt';
export { CalendarBlank } from '@phosphor-icons/react/dist/ssr/CalendarBlank';
export { ChartBar } from '@phosphor-icons/react/dist/ssr/ChartBar';
export { MapPin } from '@phosphor-icons/react/dist/ssr/MapPin';
export { Phone } from '@phosphor-icons/react/dist/ssr/Phone';
export { CaretLeft } from '@phosphor-icons/react/dist/ssr/CaretLeft';
export { CaretRight } from '@phosphor-icons/react/dist/ssr/CaretRight';
export { Check } from '@phosphor-icons/react/dist/ssr/Check';
export { X } from '@phosphor-icons/react/dist/ssr/X';
export { Plus } from '@phosphor-icons/react/dist/ssr/Plus';
export { PencilSimple } from '@phosphor-icons/react/dist/ssr/PencilSimple';
export { Trash } from '@phosphor-icons/react/dist/ssr/Trash';
export { Buildings } from '@phosphor-icons/react/dist/ssr/Buildings';
export { ShieldCheck } from '@phosphor-icons/react/dist/ssr/ShieldCheck';
export { Copy } from '@phosphor-icons/react/dist/ssr/Copy';
export { Sparkle } from '@phosphor-icons/react/dist/ssr/Sparkle';
export { Lightbulb } from '@phosphor-icons/react/dist/ssr/Lightbulb';
export { ArrowsClockwise } from '@phosphor-icons/react/dist/ssr/ArrowsClockwise';
export { CalendarPlus } from '@phosphor-icons/react/dist/ssr/CalendarPlus';
export { Funnel } from '@phosphor-icons/react/dist/ssr/Funnel';
export { Info } from '@phosphor-icons/react/dist/ssr/Info';
export { Crown } from '@phosphor-icons/react/dist/ssr/Crown';
export { DownloadSimple } from '@phosphor-icons/react/dist/ssr/DownloadSimple';
export { UploadSimple } from '@phosphor-icons/react/dist/ssr/UploadSimple';
export { Lock } from '@phosphor-icons/react/dist/ssr/Lock';
export { Key } from '@phosphor-icons/react/dist/ssr/Key';
export { WifiSlash } from '@phosphor-icons/react/dist/ssr/WifiSlash';
export { Printer } from '@phosphor-icons/react/dist/ssr/Printer';

